// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWYXtotDa8emtUEUV09S_pP0lOCavcsac',
    appId: '1:138050183999:web:cddcbd9d2238a7f470a98a',
    messagingSenderId: '138050183999',
    projectId: 'lnclusivefit',
    authDomain: 'lnclusivefit.firebaseapp.com',
    storageBucket: 'lnclusivefit.firebasestorage.app',
    measurementId: 'G-CTN9BP7BES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQDHWMHYHjqUD8-9P7jL-GNwbwZ6SJVUg',
    appId: '1:138050183999:android:0ec12d7b96616b2570a98a',
    messagingSenderId: '138050183999',
    projectId: 'lnclusivefit',
    storageBucket: 'lnclusivefit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBspP31y64_TUHaWMkqCs67KQLQi9UTtCE',
    appId: '1:138050183999:ios:b8d7859deacfeb9070a98a',
    messagingSenderId: '138050183999',
    projectId: 'lnclusivefit',
    storageBucket: 'lnclusivefit.firebasestorage.app',
    iosBundleId: 'com.example.inclusivefitSimple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBspP31y64_TUHaWMkqCs67KQLQi9UTtCE',
    appId: '1:138050183999:ios:b8d7859deacfeb9070a98a',
    messagingSenderId: '138050183999',
    projectId: 'lnclusivefit',
    storageBucket: 'lnclusivefit.firebasestorage.app',
    iosBundleId: 'com.example.inclusivefitSimple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWYXtotDa8emtUEUV09S_pP0lOCavcsac',
    appId: '1:138050183999:web:b3f727a2827e730470a98a',
    messagingSenderId: '138050183999',
    projectId: 'lnclusivefit',
    authDomain: 'lnclusivefit.firebaseapp.com',
    storageBucket: 'lnclusivefit.firebasestorage.app',
    measurementId: 'G-PSBEH9MK3L',
  );
}
